### ISSUE TITLE
Commander Module

### ISSUE THREAD

**Issue by insanity54** [insanity54/futureporn#105]
(military otaku jargon activate)

Futureporn units are as follows

* capture
* scout
* qa

Commander has a bird's eye view of the battlefield, listening in on remote actions from Futureporn worker units. Commander uses this intel to coordinate the next moves the system will take.

Commander runs a Postgres server which facilitates NOTIFY/LISTEN messaging between Futureporn units

Commander maintains a list of ongoing actions carried out by in-field units.

## TODO

* [ ] #13 
* [ ] After build, delete vods older than 24h

### Workflow

* [ ] GET tweet data and INSERT into db (futureporn/scout)
* [ ] GET CB title (futureporn/scout)
* [x] Capture (futureporn/capture)
* [ ] Signal end (futureporn/scout)
* [x] Elect capture instance with best VOD (futureporn/commander)
* [ ] concat & IPFS upload (futureporn/capture)
* [ ] NOTIFY capture/vod/upload (futureporn/capture)
* [ ] LISTEN capture/vod/upload (futureporn/builder)
* [ ] merge tweet data with vod data (futureporn/builder)
* [ ] git add (futureporn/builder)
* [ ] git commit (futureporn/builder)
* [ ] git push origin main (futureporn/builder)

**Comment by insanity54** [comment]
Aedes is yoinked
MQTT is yoinked
Redis idea is yoinked
"real database" time. PostgreSQL db has everything we need, including pub/sub

**Comment by insanity54** [comment]
I think it's too confusing to have so many different LISTEN/NOTIFY specifications. Also I think it uses 1 network connection per, so it's potentially resource intensive.

maybe 1 LISTEN/NOTIFY with all different events sent across it

**Comment by insanity54** [comment]
This is not planned anymore. Strapi acts as the central point of knowledge rn so I'll close this for now
