### ISSUE TITLE
VOD publishing is not automatic

### ISSUE THREAD

**Issue by insanity54** [insanity54/futureporn#14]
There was a time when VOD processing and publishing was 100% automatic. There's been some regression, some code functions broke, and now the process is manual. This goes against one of the original project goals which was to be FAST; the first service to publish Mel's CB vods.

Here's the plan for restoring automatic VOD publishing.

* [x] Implement #12 which creates the VOD markdown file necessary for HTML rendering
* [ ] Implement #13 which handles a corner case that would otherwise be a show-stopper
* [ ] Implement functionality which instructs futureporn.js to run ( possibly #15 )
* [ ] Implement `git add`, `git commit`, `git push origin main` which occurs automatically after futureporn.js runs. I'm not used to robots running git commands. so I'm not sure what the best practice is here. More research on this step is needed.
